export type OrderMenuItem = {
  id: string
  name: string
  description: string
  priceCents: number
  category: string
  tags?: string[]
  popular?: boolean
}

export const ORDER_MENU_CATEGORIES = [
  { id: "aperitif", label: "Aperitif" },
  { id: "antipasti", label: "Antipasti" },
  { id: "salads", label: "Salate" },
  { id: "pizza", label: "Pizza" },
  { id: "pasta", label: "Pasta" },
  { id: "risotto", label: "Risotto" },
  { id: "glutenfree", label: "Glutenfrei" },
  { id: "meat", label: "Fleisch" },
  { id: "fish", label: "Fisch" },
  { id: "dolci", label: "Dolci" },
  { id: "hot-drinks", label: "Heissgetraenke" },
  { id: "cold-drinks", label: "Kalte Getraenke" },
  { id: "water", label: "Wasser" },
  { id: "beer", label: "Bier" },
  { id: "longdrinks", label: "Longdrinks" },
  { id: "spirits", label: "Spirituosen" },
  { id: "wine", label: "Wein" },
]

function item(
  id: string,
  category: string,
  name: string,
  description: string,
  priceCents: number,
  tags: string[] = [],
  popular = false,
): OrderMenuItem {
  return {
    id,
    category,
    name,
    description,
    priceCents,
    ...(tags.length ? { tags } : {}),
    ...(popular ? { popular } : {}),
  }
}

export const ORDER_MENU_ITEMS: OrderMenuItem[] = [
  item(
    "martini-bianco-rosso-dry",
    "aperitif",
    "Martini bianco, rosso oder dry",
    "5 cl Martini nach Wahl.",
    750,
    ["5 cl"],
  ),
  item(
    "campari-soda",
    "aperitif",
    "Campari-Soda",
    "4 cl Campari mit Mineralwasser.",
    800,
    ["4 cl"],
  ),
  item(
    "campari-orange",
    "aperitif",
    "Campari-Orange",
    "4 cl Campari mit Orangensaft.",
    900,
    ["4 cl"],
  ),
  item(
    "aperol-spritz",
    "aperitif",
    "Aperol-Spritz",
    "Aperol mit Prosecco, Soda und Orange. Glas 0,20 l.",
    900,
    ["0,20 l"],
    true,
  ),
  item(
    "hugo",
    "aperitif",
    "Hugo",
    "Prosecco mit Holundersirup, Soda und Minze. Glas 0,20 l.",
    900,
    ["0,20 l"],
  ),

  item(
    "mozzarella-di-bufala",
    "antipasti",
    "Mozzarella di bufala, rucola, pomodorini",
    "Bueffelmozzarella auf Rucolabett mit Kirschtomaten.",
    1690,
    ["vegetarisch"],
  ),
  item(
    "vitello-tonnato",
    "antipasti",
    "Vitello Tonnato",
    "Zarte Kalbfleischscheiben mit Kapernapfeln in Thunfischsauce.",
    1790,
    [],
    true,
  ),
  item(
    "carpaccio-di-manzo",
    "antipasti",
    "Carpaccio di Manzo",
    "Duenn geschnittenes Rinderfilet mit Champignons, Parmesan, Zitrone und Olivenoel.",
    1790,
  ),
  item(
    "carpaccio-di-polpo",
    "antipasti",
    "Carpaccio di Polpo",
    "Octopus-Carpaccio mit Oliven und Petersilie in Zitronen-Olivenoel.",
    1790,
  ),
  item(
    "antipasti-misto-per-due",
    "antipasti",
    "Antipasti Misto per due",
    "Gemischter Vorspeisenteller fuer zwei Personen.",
    2690,
    ["fuer 2"],
    true,
  ),

  item(
    "insalata-mista",
    "salads",
    "Insalata Mista",
    "Gemischter Salat mit Kirschtomaten, Gurken und Rucola.",
    890,
    ["vegetarisch"],
  ),
  item(
    "insalata-rucola-parmigiano",
    "salads",
    "Insalata Rucola e Parmigiano",
    "Rucolasalat mit Kirschtomaten und gehobeltem Parmesan in Balsamicocreme.",
    1390,
    ["vegetarisch"],
  ),
  item(
    "insalata-primavera",
    "salads",
    "Insalata Primavera",
    "Gruener Salat, Radicchio, Kirschtomaten, Mozzarella, Walnuss und Orange.",
    1290,
    ["vegetarisch"],
  ),
  item(
    "insalata-pollo-cesare",
    "salads",
    "Insalata di Pollo Cesare con crostini",
    "Gemischter Salat mit Haehnchenbruststreifen, Kirschtomaten, Oliven, Caesar-Dressing und Grissini.",
    1490,
    [],
    true,
  ),
  item(
    "insalata-mista-scampi",
    "salads",
    "Insalata Mista con Scampi",
    "Gemischter Salat mit 3 Scampi, gebraten in Olivenoel und Kraeutern.",
    1890,
    [],
    true,
  ),

  item(
    "pizza-mozzarella",
    "pizza",
    "Pizza Mozzarella",
    "Mozzarella, Tomatensauce und Basilikum.",
    1190,
    ["vegetarisch"],
    true,
  ),
  item(
    "pizza-salami",
    "pizza",
    "Pizza Salami",
    "Mozzarella, Tomatensauce und Salami.",
    1290,
  ),
  item(
    "pizza-diavolo",
    "pizza",
    "Pizza Diavolo",
    "Mozzarella, Tomatensauce, Spianata, Peperoncini und Oliven.",
    1390,
    ["pikant"],
    true,
  ),
  item(
    "pizza-zia-anna",
    "pizza",
    "Pizza Zia Anna",
    "Mozzarella, Tomatensauce, Auberginen, Ricotta, getrocknete Tomaten und Basilikum.",
    1490,
    ["vegetarisch"],
  ),
  item(
    "pizza-gourmet-bianca",
    "pizza",
    "Pizza Gourmet bianca",
    "Mozzarella, Birnen, Walnuesse und Gorgonzola.",
    1490,
    ["vegetarisch"],
  ),
  item(
    "pizza-crudaiola",
    "pizza",
    "Pizza Crudaiola",
    "Mozzarella, Tomatensauce, Rucola, Parmaschinken, Kirschtomaten und Parmigiano.",
    1590,
    [],
    true,
  ),
  item(
    "pizza-tonno-mediterrane",
    "pizza",
    "Pizza Tonno Mediterrane",
    "Mozzarella, Tomatensauce, Thunfisch und rote Zwiebel.",
    1490,
  ),

  item(
    "spaghetti-aglio-olio-peperoncino",
    "pasta",
    "Spaghetti Aglio, Olio e Peperoncino",
    "Spaghetti mit Knoblauch, Olivenoel, Peperoncini und Petersilie.",
    1290,
    ["vegetarisch", "pikant"],
  ),
  item(
    "spaghetti-scampi-zucchini",
    "pasta",
    "Spaghetti Scampi flambati e Zucchini",
    "Spaghetti mit flambierten Garnelen, Zucchini, Knoblauch und Kirschtomaten.",
    1790,
    [],
    true,
  ),
  item(
    "penne-punto-di-filetto",
    "pasta",
    "Penne Punto di Filetto",
    "Penne mit argentinischem Rinderfilet, Champignons und roten Zwiebeln in leichter Tomatensauce.",
    1690,
  ),
  item(
    "penne-sorrento",
    "pasta",
    "Penne Sorrento",
    "Penne mit frischem Bueffelmozzarella, Tomaten und Basilikum.",
    1490,
    ["vegetarisch"],
  ),
  item(
    "penne-arrabbiata",
    "pasta",
    "Penne all'Arrabbiata",
    "Penne mit Petersilie und Knoblauch in pikanter Tomatensauce.",
    1390,
    ["vegetarisch", "pikant"],
  ),
  item(
    "tagliatelle-salmone-asparagi",
    "pasta",
    "Tagliatelle Salmone e Asparagi Verdi",
    "Tagliatelle mit frischem Lachs, gruenem Spargel, Basilikum und Olivenoel.",
    1690,
  ),
  item(
    "tagliolini-filetto-manzo-tartufo",
    "pasta",
    "Tagliolini Filetto di Manzo e Crema Tartufata",
    "Hausgemachte Tagliolini mit Rinderfiletspitzen in Butter-Trueffel-Cremesauce und Parmesan.",
    1990,
    [],
    true,
  ),
  item(
    "gnocchi-ripieni-tartufo",
    "pasta",
    "Gnocchi ripieni di tartufo",
    "Hausgemachte Gnocchi mit Ziegenkaesefuellung in Trueffel-Cremesauce.",
    1690,
    ["vegetarisch"],
    true,
  ),
  item(
    "triangoloni-rote-beete",
    "pasta",
    "Triangoloni",
    "Rote-Beete-Teig, gefuellt mit Ziegenkaese und Honig, in Butter-Salbei-Sauce.",
    1990,
    ["vegetarisch"],
  ),

  item(
    "risotto-porcini-gamberi",
    "risotto",
    "Risotto Porcini e Gamberi",
    "Risotto mit Steinpilzen, Garnelen, Olivenoel und gehobeltem Grana Padano.",
    1790,
  ),
  item(
    "risotto-gemuese-safran",
    "risotto",
    "Risotto mit verschiedenen Gemuese",
    "Risotto mit verschiedenen Gemuese in Safransauce und Parmesan.",
    1690,
    ["vegetarisch"],
  ),

  item(
    "penne-glutenfrei-rinderfilet",
    "glutenfree",
    "Penne Glutenfrei mit Rinderfilet",
    "Glutenfreie Penne mit Rinderfilet, Champignons und Tomatensauce.",
    2190,
    ["glutenfrei"],
  ),
  item(
    "penne-glutenfrei-arrabbiata",
    "glutenfree",
    "Penne Glutenfrei Arrabbiata",
    "Glutenfreie Penne mit pikanter Tomatensauce.",
    1990,
    ["glutenfrei", "vegetarisch", "pikant"],
  ),
  item(
    "penne-glutenfrei-lachs-zucchini",
    "glutenfree",
    "Penne Glutenfrei mit Lachs und Zucchini",
    "Glutenfreie Penne mit Lachs und Zucchini.",
    2190,
    ["glutenfrei"],
  ),

  item(
    "scaloppina-pollo-gorgonzola",
    "meat",
    "Scaloppina Di Pollo al Gorgonzola",
    "Haehnchenbrustfilet in leichter Gorgonzolasauce, mit Tagesgemuese und Rosmarinkartoffeln.",
    2390,
  ),
  item(
    "saltimbocca-romana",
    "meat",
    "Saltimbocca Romana",
    "Kalbsmedaillons mit Parmaschinken in Weisswein-Salbei-Butter, mit Tagesgemuese und Rosmarinkartoffeln.",
    2890,
  ),
  item(
    "filetto-manzo-griglia",
    "meat",
    "Filetto di Manzo alla Griglia",
    "Argentinisches Rinderfilet vom Grill mit Kraeuterbutter, Tagesgemuese und Rosmarinkartoffeln.",
    3790,
    [],
    true,
  ),
  item(
    "filetto-manzo-pepe-verde",
    "meat",
    "Filetto Di Manzo Al Pepe Verde",
    "Argentinisches Rinderfilet in gruener Pfeffersauce, mit Tagesgemuese und Rosmarinkartoffeln.",
    3890,
  ),
  item(
    "filetto-manzo-barolo",
    "meat",
    "Filetto Di Manzo al Barolo",
    "Argentinisches Rinderfilet in Barolo-Rotweinsauce, mit Tagesgemuese und Rosmarinkartoffeln.",
    3990,
  ),
  item(
    "mare-e-monti-duetto",
    "meat",
    "Mare E Monti (Duetto)",
    "Rinderfiletmedaillons in Rotwein-Honig und Scampi in gruener Pfeffersauce.",
    4290,
    [],
    true,
  ),
  item(
    "bisteca-paillard",
    "meat",
    "Bisteca (Paillard)",
    "Argentinisches Rumpsteak mit Tomaten, Kapern und Kraeutern, mit Tagesgemuese und Rosmarinkartoffeln.",
    2890,
  ),
  item(
    "tagliata-di-manzo",
    "meat",
    "Tagliata di Manzo",
    "Argentinisches Roastbeef, rosa tranchiert, auf Rucola und Grana Padano.",
    2890,
    [],
    true,
  ),

  item(
    "filetto-orata-livornese",
    "fish",
    "Filetto di orata alla livornese",
    "Doradenfilet Livornese mit Kapern, Oliven, Kirschtomaten, Knoblauch und Basilikum.",
    2690,
  ),
  item(
    "orata-griglia",
    "fish",
    "Orata alla Griglia",
    "Dorade im Ganzen vom Grill mit Kraeutern und Olivenoel.",
    2690,
  ),
  item(
    "filetto-salmone-griglia",
    "fish",
    "Filetto di Salmone alla Griglia",
    "Frisches Lachsfilet vom Grill mit Olivenoel und Zitrone.",
    2890,
  ),
  item(
    "filetto-salmone-burro-limone",
    "fish",
    "Filetto di salmone in salsa burro-limone",
    "Frisches Lachsfilet in Butter-Zitronensauce.",
    2890,
  ),
  item(
    "scampi-griglia",
    "fish",
    "Scampi alla Griglia",
    "Scampi vom Grill mit Knoblauch, Petersilie und Olivenoel.",
    3390,
    [],
    true,
  ),
  item(
    "scampi-prosecco",
    "fish",
    "Scampi al Prosecco",
    "Scampi flambiert in Prosecco mit Kirschtomaten, Knoblauch und Kraeutern.",
    3390,
  ),

  item(
    "souffle-cioccolato-vaniglia",
    "dolci",
    "Souffle al cioccolato con gelato di vaniglia",
    "Schokosouffle mit Vanilleeis.",
    850,
  ),
  item(
    "tiramisu",
    "dolci",
    "Tiramisu",
    "Hausgemachtes italienisches Tiramisu.",
    850,
    [],
    true,
  ),
  item(
    "panna-cotta",
    "dolci",
    "Panna Cotta",
    "Panna Cotta auf Beerensauce.",
    850,
  ),

  item("caffe", "hot-drinks", "Caffe - Tasse", "Heisses Kaffeegetraenk.", 390),
  item("espresso", "hot-drinks", "Espresso - Tasse", "Espresso.", 390),
  item("double-espresso", "hot-drinks", "Double Espresso - Tasse", "Doppelter Espresso.", 490),
  item("cappuccino", "hot-drinks", "Cappuccino - Tasse", "Cappuccino.", 450),
  item("latte-macchiato", "hot-drinks", "Latte Macchiato - Glas", "Latte Macchiato.", 490),
  item("tee", "hot-drinks", "Tee verschiedene Sorten 0,2 l", "Tee, verschiedene Sorten.", 450, ["0,2 l"]),

  item("coca-cola-020", "cold-drinks", "Coca-Cola 0,20 l", "Kalte Coca-Cola.", 350, ["0,20 l"]),
  item("coca-cola-040", "cold-drinks", "Coca-Cola 0,40 l", "Kalte Coca-Cola.", 490, ["0,40 l"]),
  item("coca-cola-light-020", "cold-drinks", "Coca-Cola Light 0,20 l", "Kalte Coca-Cola Light.", 350, ["0,20 l"]),
  item("coca-cola-light-040", "cold-drinks", "Coca-Cola Light 0,40 l", "Kalte Coca-Cola Light.", 490, ["0,40 l"]),
  item("coca-cola-zero-020", "cold-drinks", "Coca-Cola Zero 0,20 l", "Kalte Coca-Cola Zero.", 350, ["0,20 l"]),
  item("coca-cola-zero-040", "cold-drinks", "Coca-Cola Zero 0,40 l", "Kalte Coca-Cola Zero.", 490, ["0,40 l"]),
  item("fanta-020", "cold-drinks", "Fanta 0,20 l", "Fanta.", 350, ["0,20 l"]),
  item("fanta-040", "cold-drinks", "Fanta 0,40 l", "Fanta.", 490, ["0,40 l"]),
  item("sprite-020", "cold-drinks", "Sprite 0,20 l", "Sprite.", 350, ["0,20 l"]),
  item("sprite-040", "cold-drinks", "Sprite 0,40 l", "Sprite.", 490, ["0,40 l"]),
  item("schweppes-020", "cold-drinks", "Schweppes 0,20 l", "Tonic Water, Bitter Lemon oder Ginger Ale.", 350, ["0,20 l"]),
  item("schweppes-040", "cold-drinks", "Schweppes 0,40 l", "Tonic Water, Bitter Lemon oder Ginger Ale.", 550, ["0,40 l"]),
  item("apfelschorle-020", "cold-drinks", "Apfelschorle 0,20 l", "Apfelschorle.", 350, ["0,20 l"]),
  item("apfelschorle-040", "cold-drinks", "Apfelschorle 0,40 l", "Apfelschorle.", 490, ["0,40 l"]),
  item("apfelsaft-020", "cold-drinks", "Apfelsaft 0,20 l", "Apfelsaft.", 350, ["0,20 l"]),
  item("apfelsaft-040", "cold-drinks", "Apfelsaft 0,40 l", "Apfelsaft.", 490, ["0,40 l"]),
  item("orangensaft-020", "cold-drinks", "Orangensaft 0,20 l", "Orangensaft.", 350, ["0,20 l"]),
  item("orangensaft-040", "cold-drinks", "Orangensaft 0,40 l", "Orangensaft.", 490, ["0,40 l"]),
  item("mangosaft-020", "cold-drinks", "Mangosaft 0,20 l", "Mangosaft.", 350, ["0,20 l"]),
  item("mangosaft-040", "cold-drinks", "Mangosaft 0,40 l", "Mangosaft.", 490, ["0,40 l"]),
  item(
    "san-pellegrino-limonaden-bio",
    "cold-drinks",
    "San Pellegrino Limonaden Bio 0,275 l",
    "Bio-Limonade von San Pellegrino.",
    350,
    ["0,275 l"],
  ),

  item("san-pellegrino-mineralwasser-025", "water", "S.Pellegrino Mineralwasser 0,25 l", "Mineralwasser mit Kohlensaeure.", 350, ["0,25 l"]),
  item("san-pellegrino-mineralwasser-075", "water", "S.Pellegrino Mineralwasser 0,75 l", "Mineralwasser mit Kohlensaeure.", 850, ["0,75 l"]),
  item("acqua-panna-025", "water", "Acqua Panna stilles Wasser 0,25 l", "Stilles Wasser.", 350, ["0,25 l"]),
  item("acqua-panna-075", "water", "Acqua Panna stilles Wasser 0,75 l", "Stilles Wasser.", 850, ["0,75 l"]),

  item("paulaner-hell-fass-030", "beer", "Paulaner Muenchner Hell vom Fass 0,30 l", "Paulaner Muenchner Hell vom Fass.", 490, ["0,30 l"]),
  item("paulaner-hell-fass-050", "beer", "Paulaner Muenchner Hell vom Fass 0,50 l", "Paulaner Muenchner Hell vom Fass.", 650, ["0,50 l"]),
  item("hacker-pschorr-kellerbier-030", "beer", "Hacker Pschorr Kellerbier vom Fass 0,30 l", "Hacker Pschorr Kellerbier vom Fass.", 490, ["0,30 l"]),
  item("hacker-pschorr-kellerbier-050", "beer", "Hacker Pschorr Kellerbier vom Fass 0,50 l", "Hacker Pschorr Kellerbier vom Fass.", 650, ["0,50 l"]),
  item("paulaner-hefe-weissbier-naturtrueb", "beer", "Paulaner Hefe-Weissbier naturtrueb 0,50 l", "Naturtruebes Hefe-Weissbier.", 650, ["0,50 l"]),
  item("paulaner-hefe-weissbier-dunkel", "beer", "Paulaner Hefe-Weissbier dunkel 0,50 l", "Dunkles Hefe-Weissbier.", 650, ["0,50 l"]),
  item("paulaner-weissbier-kristallklar", "beer", "Paulaner Weissbier Kristallklar 0,50 l", "Kristallklares Weissbier.", 650, ["0,50 l"]),
  item("paulaner-weissbier-alkoholfrei", "beer", "Paulaner Weissbier 0,0% 0,50 l", "Alkoholfreies Weissbier.", 650, ["0,50 l", "alkoholfrei"]),
  item("paulaner-hell-alkoholfrei", "beer", "Paulaner Muenchner Hell Alkoholfrei 0,33 l", "Alkoholfreies Helles.", 490, ["0,33 l", "alkoholfrei"]),
  item("gespritztes-030", "beer", "Gespritztes 0,30 l", "Bier mit Fanta, Cola oder Sprite.", 490, ["0,30 l"]),
  item("gespritztes-050", "beer", "Gespritztes 0,50 l", "Bier mit Fanta, Cola oder Sprite.", 550, ["0,50 l"]),

  item("gin-tonic", "longdrinks", "Gin-Tonic", "Longdrink mit Softdrink und Eis auf 0,30 l aufgefuellt.", 990, ["4 cl"]),
  item("wodka-bitter-lemon", "longdrinks", "Wodka-Bitter Lemon", "Longdrink mit Softdrink und Eis auf 0,30 l aufgefuellt.", 990, ["4 cl"]),
  item("havanna-cuba-libre", "longdrinks", "Havanna Cuba Libre", "Longdrink mit Softdrink und Eis auf 0,30 l aufgefuellt.", 990, ["4 cl"]),

  item("amaretto", "spirits", "Amaretto", "Liqueur oder Amaro.", 450, ["2 cl"]),
  item("sambuca", "spirits", "Sambuca", "Liqueur oder Amaro.", 450, ["2 cl"]),
  item("limoncello", "spirits", "Limoncello", "Liqueur oder Amaro.", 450, ["2 cl"]),
  item("baileys-irish-cream", "spirits", "Baileys Irish Cream", "Liqueur oder Amaro.", 450, ["2 cl"]),
  item("ramazzotti", "spirits", "Ramazzotti", "Liqueur oder Amaro.", 450, ["2 cl"]),
  item("amaro-averna", "spirits", "Amaro Averna", "Liqueur oder Amaro.", 450, ["2 cl"]),
  item("fernet-branca", "spirits", "Fernet Branca", "Liqueur oder Amaro.", 450, ["2 cl"]),
  item("absolut-vodka", "spirits", "Absolut Vodka", "Spirituose.", 590, ["2 cl"]),
  item("vecchia-romagna", "spirits", "Vecchia Romagna", "Spirituose.", 590, ["2 cl"]),
  item("jim-beam", "spirits", "Jim Beam", "Spirituose.", 590, ["2 cl"]),
  item("havanna-club-3-jahre", "spirits", "Havanna Club 3 Jahre", "Spirituose.", 590, ["2 cl"]),
  item("grappa-hausmarke", "spirits", "Grappa Hausmarke", "Spirituose.", 590, ["2 cl"]),
  item("grappa-il-moscato", "spirits", "Grappa Il Moscato", "Spirituose.", 850, ["2 cl"]),
  item("grappa-di-amarone", "spirits", "Grappa di Amarone", "Spirituose.", 1050, ["2 cl"]),

  item("grillo-doc-glass", "wine", "Grillo D.O.C. Tenute Orestiadi 0,2 l", "Hauswein aus Sizilien, 100% Grillo.", 650, ["0,2 l", "weiss"]),
  item("grillo-doc-karafe", "wine", "Grillo D.O.C. Tenute Orestiadi 0,5 l Karaffe", "Hauswein aus Sizilien, 100% Grillo.", 1490, ["0,5 l", "weiss"]),
  item("rosato-terre-chieti-glass", "wine", "Rosato Terre di Chieti I.g.p. Venea 0,2 l", "Rosewein aus Abruzzen, 100% Montepulciano d'Abruzzo.", 650, ["0,2 l", "rose"]),
  item("rosato-terre-chieti-karafe", "wine", "Rosato Terre di Chieti I.g.p. Venea 0,5 l Karaffe", "Rosewein aus Abruzzen, 100% Montepulciano d'Abruzzo.", 1490, ["0,5 l", "rose"]),
  item("nero-davola-doc-glass", "wine", "Nero d'Avola D.o.c. Tenute Orestiadi 0,2 l", "Hauswein aus Sizilien, 100% Nero d'Avola.", 650, ["0,2 l", "rot"]),
  item("nero-davola-doc-karafe", "wine", "Nero d'Avola D.o.c. Tenute Orestiadi 0,5 l Karaffe", "Hauswein aus Sizilien, 100% Nero d'Avola.", 1490, ["0,5 l", "rot"]),
  item("bardolino-chiaretto-bottle", "wine", "Bardolino Chiaretto D.o.c. ALBINO PIONA 0,75 l", "Rosewein vom Gardasee, Corvina 80% und Rondinella 20%.", 5900, ["0,75 l", "rose", "flasche"]),
  item("valdo-prosecco-glass", "wine", "Valdo Marco Oro Prosecco D.O.C.g. 0,1 l", "Prosecco aus Valdobbiadene, 100% Glera.", 790, ["0,1 l", "prosecco"]),
  item("valdo-prosecco-bottle", "wine", "Valdo Marco Oro Prosecco D.O.C.g. 0,75 l", "Prosecco aus Valdobbiadene, 100% Glera.", 5500, ["0,75 l", "prosecco", "flasche"]),
  item("custoza-bianco-glass", "wine", "Custoza Bianco D.o.c. ALBINO PIONA 0,2 l", "Weisswein vom Gardasee: Garganega, Cortese, Pinot bianco und Chardonnay.", 790, ["0,2 l", "weiss"]),
  item("custoza-bianco-bottle", "wine", "Custoza Bianco D.o.c. ALBINO PIONA 0,75 l", "Weisswein vom Gardasee: Garganega, Cortese, Pinot bianco und Chardonnay.", 2900, ["0,75 l", "weiss", "flasche"]),
  item("pinot-grigio-glass", "wine", "Pinot Grigio IGT Di Lenardo 0,2 l", "Weisswein aus Friaul, kraeftig und voll.", 790, ["0,2 l", "weiss"]),
  item("pinot-grigio-bottle", "wine", "Pinot Grigio IGT Di Lenardo 0,75 l", "Weisswein aus Friaul, kraeftig und voll.", 2900, ["0,75 l", "weiss", "flasche"]),
  item("scaia-bianco-glass", "wine", "Scaia Bianco I.g.t. Tenuta Sant'Antonio 0,2 l", "Weisswein aus Veneto: Garganega und Chardonnay.", 790, ["0,2 l", "weiss"]),
  item("scaia-bianco-bottle", "wine", "Scaia Bianco I.g.t. Tenuta Sant'Antonio 0,75 l", "Weisswein aus Veneto: Garganega und Chardonnay.", 2900, ["0,75 l", "weiss", "flasche"]),
  item("gavi-sartirano-bottle", "wine", "Serre dei Roveri Gavi del Comune di Gavi DOCG 0,75 l", "Weisswein aus Piemonte, Cortese.", 3300, ["0,75 l", "weiss", "flasche"]),
  item("sauvignon-blanc-di-lenardo-bottle", "wine", "Sauvignon Blanc IGT Di Lenardo 0,75 l", "Weisswein aus Friaul, Sauvignon Blanc.", 3300, ["0,75 l", "weiss", "flasche"]),
  item("lugana-ca-dei-frati-bottle", "wine", "Lugana Ca dei Frati D.O.C. 0,75 l", "Weisswein aus der Lombardei, 100% Trebbiano.", 5900, ["0,75 l", "weiss", "flasche"]),
  item("barbera-appassimento-glass", "wine", "Serre dei Roveri Appassimento Barbera 0,2 l", "Rotwein aus Piemonte, Barbera.", 790, ["0,2 l", "rot"]),
  item("barbera-appassimento-bottle", "wine", "Serre dei Roveri Appassimento Barbera 0,75 l", "Rotwein aus Piemonte, Barbera.", 3100, ["0,75 l", "rot", "flasche"]),
  item("doppio-passo-primitivo-glass", "wine", "Doppio Passo Primitivo Salento I.g.t. 0,2 l", "Rotwein aus Apulien, Zinfandel und Primitivo.", 790, ["0,2 l", "rot"]),
  item("doppio-passo-primitivo-bottle", "wine", "Doppio Passo Primitivo Salento I.g.t. 0,75 l", "Rotwein aus Apulien, Zinfandel und Primitivo.", 3100, ["0,75 l", "rot", "flasche"]),
  item("chianti-castello-toscano-bottle", "wine", "Chianti \"Castello Toscano\" DOCG 0,75 l", "Rotwein aus Toskana, 100% Sangiovese.", 3500, ["0,75 l", "rot", "flasche"]),
  item("primitivo-manduria-60-anni-bottle", "wine", "Primitivo di Manduria 60 Anni D.O.P. 0,75 l", "Rotwein aus Apulien, Cant. San Marzano.", 7900, ["0,75 l", "rot", "flasche"]),
  item("amaranta-montepulciano-bottle", "wine", "AMARANTA Montepulciano d'Abruzzo 0,75 l", "Rotwein aus Abruzzen, Tenuta Ulisse.", 8900, ["0,75 l", "rot", "flasche"]),
  item("barolo-serre-roveri-bottle", "wine", "Serre dei Roveri Barolo DOCG 0,75 l", "Rotwein aus Piemont, Nebbiolo.", 8900, ["0,75 l", "rot", "flasche"]),
  item("brunello-montalcino-bottle", "wine", "Brunello di Montalcino DOCG 0,75 l", "Rotwein aus Toscana, Sangiovese.", 9300, ["0,75 l", "rot", "flasche"]),
]

export function formatCurrency(cents: number) {
  return new Intl.NumberFormat("de-DE", {
    style: "currency",
    currency: "EUR",
  }).format(cents / 100)
}
